### PR TITLE
[WFLY-17608] Add a basic structure for a design docs section

### PR DESCRIPTION
**Pull request by bstansberry**
https://issues.redhat.com/browse/WFLY-17608

Also includes a port of https://web.archive.org/web/20200508233035/https://developer.jboss.org/wiki/LayeredDistributionsAndModulePathOrganization

### CODE REVIEW

**Comment by jamezp** [comment]
Do we want to also convert the adoc to html?

**Comment by bstansberry** [comment]
@jamezp In WFLY-17608 I say

"At this point no fancy behavior or conversion of content to html, beyond what GitHub pages already does for the site as a whole, is in scope. The purpose of this section is to preserve for posterity the design thinking behind various aspects of WildFly."

I'd prefer not to block on doing anything further, and just see what github does for us. And if we we're not satisfied with what GH does, unless html conversion was automatic and required no effort beyond merging the adoc, I'm not enthused by the idea of adding requirements on authors or mergers.

https://github.com/bstansberry/wildfly.github.io/blob/WFLY-17608/wildfly-designs/LayeredDistributionsAndModulePathOrganization.adoc is quite readable, so if just reading the adoc from this repo is how the intended readers (WF devs and real power users) consume it, I think that's still an important step forward.

**Comment by bstansberry** [comment]
BTW if there's a fast way to do something better, e.g. creating a different repo and federating it into docs.wildfly.org, that's fine with me. I just don't want to block on something that may not get done for a long time.

**Comment by jamezp** [comment]
Got it. In that case I say we merge it and see what happens. I'll do some looking into if there is some way to use an action too. Maybe we could change to using different branch for hosting which an action could deal with committing to.

**Review by jamezp — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @jamezp -- let's see what happens. :)

**Pull request merged**
